# Generated by Django 5.1 on 2024-08-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
