# Generated by Django 5.1 on 2024-08-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_shpped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shpped',
            new_name='shipped',
        ),
    ]
